### PR TITLE
API v4 migration - updates (DO NOT MERGE)

### LINKED ISSUE #396: [Chore] api-v4 package: double entry of `@azure/functions`
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [ ] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
Not sure when this happened - I assume its just a bad merge. @glaucia86 can you take a look? 

```
 "@azure/functions": "^4.0.0",
 "@azure/functions": "^1.2.3",
```

image
**Expected behavior**

**Screenshots**

**OS (please complete the following information):**

- OS:
- OS Version:
- npm version:
- Node.js version:
- output of `azd version`:

**Additional context**

### PR DESCRIPTION
**Pull request by dfberry**
Fixes #396, #386, #350 

Changes

1) infra: secrets for cosmosdb, postgresdb, and appinsights are in keyvault
2) scripts: key vault secrets read into env for db restore
3) packages: api -> api-legacy (v3 programming model)
4) packages: api-v4 -> api (v4 programming model)
5) packages/api/src: @azure/identity -> v4.0.0
6) packages/api/src/index.ts: function names: remove duplicate and rename for function-verb 
7) packages/api/src/config/index: use appInsights

Verify changes requires the following:
1) do not deploy stripe package - this is unrelated to changes in this PR but does fail the deployment so comment out the stripe service in `azure.yml` before deploying
2) SWA ssl error - still unclear what that is - but I worked it around it by changing the URL to `http` then continuing past the warning, then it redirects to the correct SWA + data returned from Fns - it looked it @manekinekko might be looking into this

https://green-field-052295603.4.azurestaticapps.net/home

image

@glaucia86 - fyi

@manekinekko @anfibiacreativa Ready for review.

### CODE REVIEW

**Comment by glaucia86** [comment]
Thanks, @dfberry!

p.s.: just for your information, @dfberry and I made code review together this PR, once is related with the v3 to v4 migration PR

**Comment by manekinekko** [comment]
I've got a few issues when:
1. after logged in successfully, I was redirected to /home with a blank screen
2. when I clicked on a favorite button, I got a 500 error on the API call
3. when I clicked on the reserve button I got the pop alerte
image

**Comment by dfberry** [comment]
Working with @jongio and @glaucia86 for infra corrections.

**Comment by diberry** [comment]
Closing - the infra updates need to be separated from the API v4.

**Pull request closed without merging**
