### PR TITLE
feat(portal): bind routed information to routed component inputs

### LINKED ISSUE #232: [Feat] [Portal] Bind routed information to routed component inputs
1. Implement `bindToComponentInputs` feature
2. Reduce unnecessary boilerplates

### PR DESCRIPTION
**Pull request by sumitparakh**
- [x] Implement `bindToComponentInputs` feature
- [x] Reduce boilerplates 

Closes #232

### CODE REVIEW

**Comment by manekinekko** [comment]
Hi @sumitparakh it looks like there is an issue with these changes. After running the app, and navigating as a Guest to a random listing, I have this error.
image

**Comment by sumitparakh** [comment]
Hi @manekinekko,

Weird but I am not getting any error while navigating any random listing in Guest mode: -
image


PS: I am running entire application locally and not from vs codespace.

**Comment by manekinekko** [comment]
@sumitparakh  I am still unable to make these changes work inside of Codespaces. Would you like to give it a try?

**Comment by sumitparakh** [comment]
> @sumitparakh  I am still unable to make these changes work inside of Codespaces. Would you like to give it a try?

Ok. I will check

**Comment by manekinekko** [comment]
Hi @sumitparakh what's the status of this PR?

**Comment by sumitparakh** [comment]
Hi @manekinekko, I resolved merge conflicts but still couldn't reproduce this issue you are facing. I tried in both normal and incognito mode but no luck. Can you recheck? Is everyone in your team facing this issue?

**Comment by manekinekko** [comment]
Thanks @sumitparakh. Let me try it again and get back to you.

**Review by manekinekko — APPROVED** [review]

**Comment by sumitparakh** [comment]
Finally 🤩

**Pull request merged**
