### PR TITLE
fix: fixed typo in contrubuting.md

### LINKED ISSUE #294: [Docs] Typo in Statement: "bux fixes" should be "bug fixes"
Hello,

I came across a minor typo in the project that I'd like to report for correction. In the project's `contributing.md documentation` [Build The Project From Source](https://github.com/michaelkhanda/contoso-real-estate/blob/main/CONTRIBUTING.md#build-the-project-from-source), there's a statement that reads `"bux fixes"` instead of the correct `"bug fixes."` I believe this small error can be easily rectified to maintain consistency and accuracy in the project.

**Location of Typo:**
[Build The Project From Source](https://github.com/michaelkhanda/contoso-real-estate/blob/main/CONTRIBUTING.md#build-the-project-from-source)

**Expected Correction:**
The statement `"bux fixes"` should be corrected to read `"bug fixes."`

**Steps to Reproduce:**
1. Navigate to [Build The Project From Source](https://github.com/michaelkhanda/contoso-real-estate/blob/main/CONTRIBUTING.md#build-the-project-from-source).
2. Observe the statement `"bux fixes."`

**Proposed Solution:**
I recommend locating the instance of the typo and replacing `"bux fixes"` with `"bug fixes."` This small correction will help maintain the project's professional appearance and avoid confusion among users.

Thank you for considering this issue, and I'm looking forward to contributing to the improvement of the project!

**Labels:**
- `e2e-docs`
- typo

### PR DESCRIPTION
**Pull request by kelvink96**
Fixes #294

Renamed bux to bug in contributing.md

### CODE REVIEW

**Review by anfibiacreativa — APPROVED** [review]
Thanks for your contribution!

**Comment by michaelkhanda** [comment]
Thank you for that @kelvink96 . I had made a pull request on the same but it was not merged. Let us continue contributing.

**Comment by anfibiacreativa** [comment]
Hi @michaelkhanda , we're doing our best to track collaborators but this one slipped. Whenever a fix is approved for an issue reported, we will give the contributor badge to both the reporter and the one pushing the code. Please keep on contributing! There are plenty of potential issues to go for! Thank you!

**Comment by michaelkhanda** [comment]
Hi there! @anfibiacreativa , Thanks for addressing this and keeping us updated, it's great to see the commitment to maintaining the quality of collaboration. We appreciate the effort to ensure both reporters and code contributors receive their well-deserved recognition. I'll definitely keep contributing and exploring the potential issues. Exciting times are ahead! Thank you again for the support and encouragement! 🙌👏

**Pull request merged**
