### PR TITLE
docs: update README.md samples frontmatter

### PR DESCRIPTION
**Pull request by anfibiacreativa**
This potentially fixes inclusion in sample's dir

### CODE REVIEW

**Comment by diberry** [comment]
@anfibiacreativa These changes would impact a customer's ability to find this sample. Were you guided to remove the name, and description by someone on the samples browser team?

**Comment by anfibiacreativa** [comment]
> @anfibiacreativa These changes would impact a customer's ability to find this sample. Were you guided to remove the name, and description by someone on the samples browser team?

Hi Dina, maybe the problem is different, but the sample is not currently showing in the site. I tried to validate some of the service tags with those of samples that are indeed being returned by a query. Please correct me if wrong and if you have a list of accepted tags we may have to verify we don't have some formatting typo...

**Comment by diberry** [comment]
I'm going to track it down.
________________________________

**Comment by anfibiacreativa** [comment]
> I'm still tracking this down. The sample was ingested yesterday but it seems to have dropped off the repo.

What's the current status?

**Comment by diberry** [comment]
The sample has been onboarded - https://learn.microsoft.com/en-us/samples/browse/?terms=contoso. You don't need this PR but if you feel it is more accurate, merge it.

**Pull request closed without merging**
