### PR TITLE
fix: fixed sign-in buttons change background color after reloading the page #279

### LINKED ISSUE #279: [Hack-together] Sign-in buttons change background color after reloading the page
**Are you accessing the project from the GitHub Codespaces?**

- [ ] No, I am running the project on my local machine (I will fill in the OS section below)
- [x] Yes, I am using GitHub Codespaces.

> Note: The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Describe the bug**
When navigating to the login page of the portal using the *login* button, all the sign-in buttons appear with their specific background color.
However, after reloading the page, the sign-in buttons all have a white background.
The same thing happens if I navigate directly to the `/auth/login`.

**To Reproduce**

1. Run the application with `npm run start`
2. Open the portal app
3. Click on *Welcome, Guest* on the top right side of the home page, and then *Login*
4. Press F5 or reload the page
5. The sign-in buttons have a white background

**Expected behavior**
The buttons shouldn't change color when reloading the page.

**Screenshots**

image

image

**OS (please complete the following information):**

- OS: Linux
- OS Version: codespaces-a87b53 5.15.0-1042-azure
- npm version: 9.8.1
- Node.js version: v18.15.0
- output of `azd version`: azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Additional context**
None.

### PR DESCRIPTION
**Pull request by error9098x**
Fixes #279 Regarding the Sign-In Button Bug

I attempted several approaches to resolve it, but I couldn't determine why the existing CSS was suddenly being overridden. While using `!important` would have been a quick solution, it's not considered a best practice. Instead, I enhanced the CSS styles by making them more specific, assigning unique IDs to each button, such as #google for the Google button, like so:

`<a *ngFor="let provider of providers" mat-raised-button id="{{provider.id}}" class="button btn__{{provider.id}}" [href]="loginWith(provider.id)">
  Sign in with {{ provider.name }}
</a>
`
If you have any concerns about the optimization and good practices, please feel free to provide guidance on alternative solutions.

If you find this approach suitable, I'm open to suggestions regarding other issues also I am open to other suggestions. :)

https://github.com/Azure-Samples/contoso-real-estate/assets/43810146/451d4d64-edc1-4c13-95bc-eedb19bbf3d2

@juliamuiruri4  
Also, do I have to anything else to make it count as my hack-together contribution?

### CODE REVIEW

**Review by anfibiacreativa — CHANGES_REQUESTED** [review]
Hi @error9098x ! Thanks for your contribution!
In an attempt to follow best practices, using ids to style elements in a page, is generally avoided. We try to use ids for functionally/behavior, and classes for styling. 

This is why, following BEM conventions, we have added the __modifier that determines the color of the button.

I would suggest we find out why this is not working. Can you please record a video of your debugging process? It is a very interesting problem to solve.

**Comment by ASP2017** [comment]
anfibiacreativa,
can you please add more details and explanation for the sentence
what is BEM conventions, regarding contoso project, and what does it the __modifier and where look for?
I do like to take it or at least to learn more about.
10x.

**Comment by richardrigutins** [comment]
I've further investigated the issue, both using the development and production configurations.

The problem is caused by a conflict between the background colors applied by `mat-mdc-raised-button:not(:disabled)` and the `btn__modifier` classes.

The order in which the styles are added to the login page when reloading is different to the one you get when navigating from the home page.

If you navigate from the home and then inspect the page in the browser, you can see that the style block containing the `btn__modifier` classes comes after the one that defines `mat-mdc-raised-button:not(:disabled)`:
image

Instead, if you refresh the page, you can see that the two blocks are in the opposite order:
image

This is probably caused by the way Angular loads styles in the page. 

Maybe you could try using a more specific css selector to increase the priority of the __modifier classes (i.e. something like `.button.btn__microsoft`)?

**Comment by anfibiacreativa** [comment]
Great analysis @richardrigutins !

**Comment by anfibiacreativa** [comment]
Hi @error9098x Will you be submitting a new fix based on @richardrigutins analysis? Let us know! Thank you!

**Comment by error9098x** [comment]
> Hi @error9098x Will you be submitting a new fix based on @richardrigutins analysis? Let us know! Thank you!

I have opened another PR #327 to resolve this issue, please take a look!

**Pull request closed without merging**
