### PR TITLE
fix(api): the route 'get-payment-by-id' is in singular change to plural

### PR DESCRIPTION
**Pull request by glaucia86**
fix(api): the route 'get-payment-by-id' is in singular. So I am changing to plural #234

### CODE REVIEW

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
I am not sure about these changes. @sinedied does this look good to you? Is switching from `payment/**` to `payments/**` break the payment API call?

**Review by sinedied — DISMISSED** [review]
Should be good, as the stripe backend only creates the payments through the payments/ endpoint.

This one isn't actually used, though you should also update the openai descriptions in both the infra/app folder and the packages/api folder.

**Comment by anfibiacreativa** [comment]
@glaucia86 will you further update the OpenAPI .yaml specification in order to merge this?

**Comment by glaucia86** [comment]
> @glaucia86 will you further update the OpenAPI .yaml specification in order to merge this?

Hi, @anfibiacreativa I can update it! Let me see here and I will keep you update!

**Comment by glaucia86** [comment]
> > @glaucia86 will you further update the OpenAPI .yaml specification in order to merge this?
> 
> Hi, @anfibiacreativa I can update it! Let me see here and I will keep you update!

@anfibiacreativa 

It seems that @sinedied made this change in the `openAPI.yaml` file 8 months ago, specifying "payment" as plural, as shown in the image below.

[](https://postimg.cc/gx4LKh4T)

**Comment by manekinekko** [comment]
Thank you @glaucia86

**Review by manekinekko — APPROVED** [review]

**Pull request merged**
