### PR TITLE
feat: made reviews visible from homepage

### PR DESCRIPTION
**Pull request by VictorCodebase**
for issue #322  (allow users to see house rating from homepage)

Each listings rating can now be easily seen from homepage

## Screenshot
image

The 296 line in listing.json is identical to the one that was there before. I dont know why its getting flagged as changed

Thanks

### CODE REVIEW

**Comment by VictorCodebase** [comment]
Im curious. Some houses have 0 star rating - which isn't very conventional. 
Should I make it in a way that 0 stars is one star?

**Comment by anfibiacreativa** [comment]
> Im curious. Some houses have 0 star rating - which isn't very conventional. Should I make it in a way that 0 stars is one star?

That was artificially generated mock data and may not be 100% sensible.

**Comment by VictorCodebase** [comment]
There are no updates. This's currently my final version. Thats unless there's something I should change or improve.

**Comment by anfibiacreativa** [comment]
hi @VictorCodebase . Thank you for your time and effort. After consideration we decided this is out of scope for the time being. We may reopen it after making the necessary changes to persist update review scores in the DB.

**Pull request closed without merging**
